import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import profile2 from "../public/profile2.jpg";
import frontend from "../public/frontend.png";
import backend from "../public/backend.png";
import niptooloofinal from "../public/niptoloofinal.jpg";
import reviewzone from "../public/reviewzone.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const [activeProject, setActiveProject] = useState(null);

  const handleToggle = (project) => {
    setActiveProject(activeProject === project ? null : project);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Darsshan Palaram Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section>
          <nav className="py-10 mb-0 flex justify-between">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center pt-10 pr-10 pl-10">
            <h2 className="text-5xl py-2 text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500 font-medium md:text-6xl">
              Darsshan Palaram
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              First-year BA Computer Science undergraduate at the University of Exeter, with a 
              strong foundation in full-stack development using Python, Java, JavaScript, PHP, and more.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 mt-10 text-gray-600 dark:text-gray-300">
            <a
              href="https://linkedin.com/in/darsshan-palaram-776783261"
              target="_blank"
              rel="noreferrer"
              alt="Linkedin"
            >
              <AiFillLinkedin className="scale-100 hover:scale-105 ease-in duration-200" />
            </a>
            <a
              href="https://github.com/DarsshanP"
              target="_blank"
              rel="noreferrer"
              alt="GitHub"
            >
              <AiFillGithub className="scale-100 hover:scale-105 ease-in duration-200" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mb-20 overflow-hidden md:h-96 md:w-96">
            <Image src={profile2} alt="Profile_picture" priority={true} className="relative -top-20"/>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I&apos;m currently an undergraduate student studying
              <span className="text-teal-500"> computer science </span> at
              the University of Exeter. Alongside my studies, I am leading the
              development of a Resource Management System for Critical Kit in order
              to streamline their workflow. I&apos;m always looking for creative solutions
              and have a strong desire to learn and grow as a developer.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Some other facts about me: I love game development and have been working on
              making my own game as a hobby. I also love to stay active by going to the gym and rock climbing.
            </p>
          </div>
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                <Image src={backend} width={100} height={100} alt="" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Programming Languages
              </h3>
              <p className="py-2 dark:text-white">
                Well-versed in multiple programming languages, while particularly skilled in Python and JavaScript.
              </p>
              <h4 className="py-4 text-teal-600">
                Languages I&apos;m familiar with:
              </h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">Python</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Java</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">JavaScript</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">PHP</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">MySQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                <Image src={frontend} width={100} height={100} alt="" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Full-Stack Development
              </h3>
              <p className="py-2 dark:text-white">
                Experience in designing and developing user-friendly interfaces, as well as
                building server-side systems, integrating databases, and working with REST APIs
                to ensure seamless and secure user experiences.
              </p>
              <h4 className="py-4 text-teal-600">
                Tools/Frameworks I&apos;m familiar with: 
              </h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">React</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">CakePHP</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Node</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">MySQL</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">GraphQL</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-gray-800 dark:text-gray-300 py-1">
              Click on an image to view more details.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row">
            {/* NipToLoo Project */}
            <div className="basis-1/3 flex-1 relative">
              <Image
                src={niptooloofinal}
                onClick={() => handleToggle("nip")}
                className="rounded-lg object-cover scale-100 hover:scale-105 ease-in duration-200 cursor-pointer"
                width={"100%"}
                height={"100%"}
                alt="The NipToLoo app"
              />
              {activeProject === "nip" && (
                <div className="absolute top-0 left-0 bg-black bg-opacity-80 text-white p-6 rounded-lg z-10 w-500 h-500 flex flex-col items-center justify-center text-center space-y-4">
                  <p>
                    NipToLoo: A mobile app that helps users find nearby public toilets,
                    built with React Native and real-time map integration.
                  </p>
                  <a
                    href="https://github.com/AngelikaM-T/NipToLoo"
                    target="_blank"
                    rel="noreferrer"
                    className="underline text-teal-300 hover:text-teal-400 transition"
                  >
                    View on GitHub →
                  </a>
                </div>
              )}
            </div>
            {/* ReviewZone Project */}
            <div className="basis-1/3 flex-1 relative">
              <Image
                src={reviewzone}
                onClick={() => handleToggle("review")}
                className="rounded-lg object-cover scale-100 hover:scale-105 ease-in duration-200 cursor-pointer"
                width={"100%"}
                height={"100%"}
                alt="The ReviewZone website"
              />
              {activeProject === "review" && (
                <div className="absolute top-0 left-0 bg-black bg-opacity-80 text-white p-6 rounded-lg z-10 w-full h-full flex flex-col items-center justify-center text-center space-y-4">
                  <p>
                    ReviewZone: A game review site built with React and REST APIs,
                    allowing users to browse, rate, and discuss games.
                  </p>
                  <a
                    href="https://github.com/DarthShan/NC-Games-Front-End"
                    target="_blank"
                    rel="noreferrer"
                    className="underline text-teal-300 hover:text-teal-400 transition"
                  >
                    View on GitHub →
                  </a>
                </div>
              )}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
